SignalR Demo/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using SignalR_Demo.Areas.HelpPage.ModelDescriptions;

namespace SignalR_Demo.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

SignalR Demo/Models/Post.cs
using System;

namespace SignalR_Demo.Models
{
    public class Post
    {
        public string FeedName { get; set; }
        public DateTime DateTime { get; set; }
        public string Body { get; set; }
        public Guid Id { get; set; }
    }
}

SignalR Demo/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using SignalR_Demo.Areas.HelpPage.ModelDescriptions;
using SignalR_Demo.Areas.HelpPage.Models;

namespace SignalR_Demo.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

SignalR Demo/Controllers/BlocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalR_Demo.Controllers
{
    public class BlocksController : Controller
    {
        // GET: Blocks
        public ActionResult Index()
        {
            return View();
        }
    }
}

SignalR Demo/Controllers/FeedsApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using SignalR_Demo.Models;

namespace SignalR_Demo.Controllers
{
    [RoutePrefix("api/feeds")]
    public class FeedsApiController : ApiController
    {
        [HttpGet]
        [Route("")]
        public IEnumerable<Post> Get()
        {
            return _repo.All();
        }

        [HttpGet]
        [Route("{id}")]
        public Post Get(Guid id)
        {
            return _repo.Get(id);
        }

        [HttpPost]
        [Route("")]
        public IHttpActionResult Post([FromBody]Post post)
        {
            _repo.Add(post);
            return Ok();
        }

        [HttpPut]
        [Route("{id}")]
        public IHttpActionResult Put([FromBody]Post post)
        {
            _repo.Update(post);
            return Ok();
        }

        [HttpDelete]
        [Route("{id}")]
        public IHttpActionResult Delete([FromBody]Post post)
        {
            _repo.Delete(post);
            return Ok();
        }
    }
}

SignalR Demo/Controllers/FeedsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SignalR_Demo.Models;

namespace SignalR_Demo.Controllers
{
    public class FeedsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SignalR Demo/Views/Blocks/Index.cshtml
<section class="hub blocks">
    <div draggable class="circle"></div>
</section>
<section class="persistent blocks">
    <div draggable class="circle"></div>
</section>
<div id="info" class="clearfix"></div>
<div id="output"></div>

@section scripts
{
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/apps/blocks")
}

SignalR Demo/Views/Feeds/Index.cshtml
<div class="feeds" ng-app="Feeds" ng-controller="List" ng-cloak>
    @*@{ Html.RenderPartial("_Add", new Feed()); }*@

    <form>
        <section class="container form-group row">
            <div class="col-md-2">
                <div class="input-group feed-{{post.FeedName}}">
                    <span class="input-group-addon">feed</span>
                    <input type="number" ng-model="post.FeedName" min="1" max="5" class="form-control" />
                </div>
            </div>
            <input type="text" ng-model="post.Body" placeholder="New Post" class="form-control col-md-2" />
            <input type="submit" ng-click="addPost()" class="btn btn-primary btn-large col-md-1" value="Post &raquo;" />
            <div class="col-md-2 input-group">
                <span class="input-group-addon">max posts</span>
                <input type="number" ng-model="wallLength" class="form-control" />
            </div>
        </section>
    </form>
    <section class="ticker clearfix">
        <ul ng-repeat="item in items | limitTo:wallLength" class="list-inline feed-{{item.FeedName}}">
            <li>Feed {{item.FeedName}}</li>
            <li>{{item.Body}}</li>
            <li>{{item.DateTime | date:'h:mm:ss a'}}</li>
        </ul>
    </section>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/apps/feeds")
}

SignalR Demo/Views/Feeds/_Post.cshtml
@model SignalR_Demo.Models.Post

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FeedName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FeedName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FeedName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SignalR Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SignalR Demo</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SignalR Demo", "Index", "Blocks", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blocks", "Index", "Blocks")</li>
                    <li>@Html.ActionLink("Feeds", "Index", "Feeds")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/scripts/util.js")
    @RenderSection("scripts", required: false)
</body>
</html>